version: "3"
services:
  dev:
    container_name: dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    environment:
      SHELL: /bin/bash
      NODE_ENV: development
    volumes:
      - "/usr/src/app/node_modules"
      - "./:/usr/src/app"
    entrypoint: ng serve --host 0.0.0.0 --poll 1
